### PR TITLE
Split travis.ci tests into fast stage then slow stage

### LINKED ISSUE #2283: Windows builds are all failing
Example: https://travis-ci.com/quantumlib/Cirq/jobs/243569608

```
$ powershell -command 'Set-MpPreference -DisableArchiveScanning $true'
The command "powershell -command 'Set-MpPreference -DisableArchiveScanning $true'" failed and exited with 1 during .
```

### PR DESCRIPTION
**Pull request by Strilanc**
- Add incremental pytest to fast stage
- Also fixes #2283

### CODE REVIEW

File: dev_tools/conf/pip-install-minimal-for-pytest-changed-files.sh [hunk 1]
```diff
@@ -0,0 +1,31 @@
+#!/usr/bin/env bash
+
+# Copyright 2018 The Cirq Developers
```
Comment (dabacon) [inline dev_tools/conf/pip-install-minimal-for-pytest-changed-files.sh]: nit: +1 to year

File: .travis.yml [hunk 2]
```diff
@@ -9,21 +9,39 @@ branches:
 before_install:
 - pip install --upgrade pip setuptools wheel
 stages:
+- quick_test
```
Comment (dabacon) [inline .travis.yml]: smoke test?
